name: Replace and Push

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Download and Replace
      run: |
        mkdir temp
        cd temp
        wget https://minicast.imbc.com/PodCast/pod.aspx?code=1000671100000100000
        sed -i 's|https://podcastfile.imbc.com/cgi-bin/podcast.fcgi/podcast/|https://podcastfiledown.imbc.com/originaldata/|g' *.xml

    - name: Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Automated text replacement"
        git push
