name: Update Podcast URL

on: 
  push:
    branches: [ main ]

jobs:
  updateURL:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download XML
        run: |
          curl -L https://minicast.imbc.com/PodCast/pod.aspx?code=1000671100000100000 -o hand-economy.xml

      - name: Replace URLs
        run: |
          sed -i.bak 's|https://podcastfile.imbc.com/cgi-bin/podcast.fcgi/podcast/|https://podcastfiledown.imbc.com/originaldata/|g' hand-economy.xml;
          rm hand-economy.xml.bak

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Updated podcast URLs"
      - name: Push changes to main branch # merge 내용들을 main 브랜치로 최종 push
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
